name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-linux-x86:
    name: Build (linux-x86)
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --init
    steps:
      - name: Install git and tar
        run: apk add --no-cache git tar gzip

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: .ci/scripts/install_dependencies_alpine.sh

      - name: Set safe git directory inside container
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run build script
        run: .ci/scripts/build_in_container.sh

      - name: Rename binary
        run: |
          mkdir -p artifacts
          cp .out/qdl artifacts/qdl-linux-x86

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qdl-linux-x86
          path: artifacts/qdl-linux-x86

  build-macos:
    name: Build (macOS)
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: macos-x86
            runner: macos-13
          - platform: macos-aarch64
            runner: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: .ci/scripts/install_dependencies_macos.sh

      - name: Run build script
        env:
          PLATFORM: ${{ matrix.platform }}
        run: .ci/scripts/build_in_container.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qdl-${{ matrix.platform }}
          path: .out/qdl-${{ matrix.platform }}.tar.gz

  build-windows:
    name: Build (Windows)
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: windows-x86
            runner: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-autotools

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        env:
          PLATFORM: ${{ matrix.platform }}
        run: .ci/scripts/build_in_container.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qdl-${{ matrix.platform }}
          path: .out/qdl-${{ matrix.platform }}.tar.gz

  release:
    name: Publish Dated Release
    needs: [build-linux-x86, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate tag
        id: generate_tag
        run: echo "tag=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.generate_tag.outputs.tag }}
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          files: |
            artifacts/qdl-linux-x86
            artifacts/qdl-macos-x86.tar.gz
            artifacts/qdl-macos-aarch64.tar.gz
            artifacts/qdl-windows-x86.tar.gz
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
